import {
	Car,
	CreditCard,
	Heart,
	Home,
	ShoppingCart,
	UtensilsCrossed,
} from 'lucide-react'

export const SYSTEM_CATEGORIES = [
	{
		cat_id: 'food',
		name: 'Food',
		type: 'expense',
		cat_icon: 'UtensilsCrossed',
		color: '#e67e22',
	},
	{
		cat_id: 'transport',
		name: 'Transport',
		type: 'expense',
		cat_icon: 'Car',
		color: '#3498db',
	},
	{
		cat_id: 'salary',
		name: 'Salary',
		type: 'income',
		cat_icon: 'CreditCard',
		color: '#9b59b6',
	},
	{
		cat_id: 'shopping',
		name: 'Shopping',
		type: 'expense',
		cat_icon: 'ShoppingCart',
		color: '#27ae60',
	},
]

export const categoryIcons = {
	Food: <UtensilsCrossed size={20} />,
	Shopping: <ShoppingCart size={20} />,
	Transport: <Car size={20} />,
	Health: <Heart size={20} />,
	Income: <CreditCard size={20} />,
	Home: <Home size={20} />,
	Other: <CreditCard size={20} />,
}

export const ICON_CHOICES = [
	'UtensilsCrossed',
	'ShoppingCart',
	'Car',
	'CreditCard',
	'UsersRound',
	'Heart',
	'Home',
	'Receipt',
	'Coffee',
	'Gift',
	'DollarSign',
	'PieChart',
	'FileText',
	'Star',
	'Gamepad2',
	'Music',
	'Film',
	'Book',
	'Camera',
	'Calendar',
	'Clock',
	'MapPin',
	'Phone',
	'Mail',
	'Globe',
	'Headphones',
	'Lightbulb',
	'Monitor',
	'Smartphone',

	'ArrowUpCircle',
	'ArrowDownCircle',
	'ArrowUpRight',
	'ArrowDownLeft',
	'TrendingUp',
	'TrendingDown',
	'Wallet',
	'WalletMinimal',
	'PiggyBank',
	'Coins',
	'BadgeDollarSign',
	'Banknote',
	'CircleDollarSign',
	'PlusCircle',
	'MinusCircle',
	'ShoppingBag',
	'ReceiptText',
	'Landmark',
	'Briefcase',
	'Handshake',
	'ListOrdered',
	'History',
	'Repeat',
	'RefreshCw',
	'ArrowLeftRight',
]
